
[options]
    default_indent = 4
# enable_debug = 1
    enable_ale = 0
    filemanager = "vimfiler"
    filetree_direction = "right"
# enable_ycm = 1
# snippet_engine = "ultisnips"
    line_on_the_fly = 0
    enable_statusline_mode = false
    realtime_leader_guide = 1
    enable_tabline_filetype_icon = false
    enable_os_fileformat_icon = false
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"
    statusline_unicode_symbols = false
    buffer_index_type = 4
    windows_index_type = 3
    statusline_separator = 'arrow'
    github_username = 'romanlarionov'
    auto_disable_touchpad = 0
# colorscheme = 'one'
    checkinstall = false
    guifont = 'SauceCodePro Nerd Font:h11:cANSI:qDRAFT'
    enable_tabline_filetype_icon = false
    search_tools = ["rg", "pt", "ack", "grep", "findstr"]
# autocomplete_method = "coc"
    commandline_prompt = '>'
# vimcompatible = true
# enable_language_specific_leader = false
    enable_statusline_tag = false

[[layers]]
    name = "cscope"

[[layers]]
    name = "lang#c"
    clang_executable = "/usr/bin/clang"
    libclang_path = "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib"
    [layer.clang_std]
        c = "c11"
        cpp = "c++11"
