
[options]
    default_indent = 4
    enable_ale = 0
    filemanager = "vimfiler"
    filetree_direction = "right"
#   enable_ycm = 1
    line_on_the_fly = 0
    realtime_leader_guide = 1
    enable_os_fileformat_icon = false
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"
    statusline_unicode_symbols = false
    buffer_index_type = 4
    windows_index_type = 3
    statusline_separator = 'arrow'
    github_username = 'romanlarionov'
    auto_disable_touchpad = 0
    checkinstall = false
    guifont = 'SauceCodePro Nerd Font:h11:cANSI:qDRAFT'
    enable_guicolors = false
    enable_tabline_filetype_icon = false
    search_tools = ["grep", "findstr", "rg", "pt", "ack"]
    commandline_prompt = '>'
    indentLine_enabled = false
    enable_statusline_mode = false
    enable_statusline_tag = true
    relativenumber = false
    max_column = 140

[[custom_plugins]]
  name = "sickill/vim-monokai"
  merged = 0

[[layers]]
    name = "tags"

[[layers]]
    name = "cscope"

[[layers]]
    name = "unite"

[[layers]]
    name = "autocomplete"
    auto-completion-delay = 10
    auto-completion-return-key-behavior = "smart"
    auto-completion-tab-key-behavior = "smart"

[[layers]]
    name = "lang#c"
    clang_executable = "/usr/bin/clang"
    libclang_path = "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib"
    [layer.clang_std]
        c = "c11"
        cpp = "c++11"
